openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: A simple user management API

servers:
  - url: /api/v1

paths:
  /slack:
    post:
      summary: "Handle Slack slash command"
      description: "Endpoint to receive Slack slash command payloads."
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              oneOf:
                - type: object
                  properties:
                    ssl_check:
                      type: string
                      enum: ["1"]
                    token:
                      type: string
                  required:
                    - ssl_check
                    - token
                - type: object
                  properties:
                    token:
                      type: string
                      description: "Verification token (deprecated)"
                    team_id:
                      type: string
                    team_domain:
                      type: string
                    enterprise_id:
                      type: string
                      nullable: true
                    enterprise_name:
                      type: string
                      nullable: true
                    channel_id:
                      type: string
                    channel_name:
                      type: string
                    user_id:
                      type: string
                    user_name:
                      type: string
                    command:
                      type: string
                      description: "The slash command that was invoked (e.g. /weather)"
                    text:
                      type: string
                      description: "Any additional text provided after the command"
                    response_url:
                      type: string
                      format: uri
                    trigger_id:
                      type: string
                    api_app_id:
                      type: string
                  required:
                    - team_id
                    - channel_id
                    - user_id
                    - command
                    - response_url
      responses:
        '200':
          description: "Successful acknowledgement with optional immediate response."
          content:
            application/json:
              schema:
                type: object
                properties:
                  response_type:
                    type: string
                    description: "Either 'ephemeral' or 'in_channel'"
                  text:
                    type: string
